required = ["github.com/gogo/protobuf/protoc-gen-gogo"]

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "0.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/zeebo/errs"

[[constraint]]
  branch = "master"
  name = "github.com/zeebo/tdigest"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/spacemonkeygo/random.v1"
