required = [
  "github.com/gogo/protobuf/protoc-gen-gogo",
]

ignored = [
	"github.com/spacemonkeygo/rothko/draw/graph/js",
]

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "0.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/zeebo/errs"

[[constraint]]
  branch = "master"
  name = "github.com/zeebo/tdigest"
