required = [
  "github.com/gogo/protobuf/protoc-gen-gogo",
]

ignored = [
	"github.com/spacemonkeygo/rothko/draw/graph/js",
]

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "0.5.0"

[[constraint]]
  name = "github.com/zeebo/errs"
  branch = "master"

[[constraint]]
  name = "github.com/zeebo/tdigest"
  branch = "master"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.7.1"
