// Copyright (C) 2017. See AUTHORS.

package dists

import "github.com/zeebo/errs"

// Error is the class that contains all the errors generated by this package.
var Error = errs.Class("dists")

// Dist is a representation of a distribution.
type Dist interface {
	// Query returns the value for the x'th percentile. The percentile is
	// represented as a number in [0, 1].
	Query(x float64) float64

	// CDF returns the percentile for the given value. The percentile is
	// represented as a number in [0, 1].
	CDF(x float64) float64

	// Len returns how many observations there were for the distribution.
	Len() int64
}
