// Copyright (C) 2017. See AUTHORS.

// package dists helps loading distributions
package dists // import "github.com/spacemonkeygo/rothko/data/dists"

import "github.com/zeebo/errs"

// Error is the class that contains all the errors generated by this package.
var Error = errs.Class("dists")

// Dist is a representation of a distribution.
type Dist interface {
	Query(x float64) float64
	Len() int64
}
