// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: data.proto

/*
	Package data is a generated protocol buffer package.

	It is generated from these files:
		data.proto

	It has these top-level messages:
		Record
*/
package data

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type DistributionKind int32

const (
	DistributionKind_Random  DistributionKind = 0
	DistributionKind_TDigest DistributionKind = 1
)

var DistributionKind_name = map[int32]string{
	0: "Random",
	1: "TDigest",
}
var DistributionKind_value = map[string]int32{
	"Random":  0,
	"TDigest": 1,
}

func (x DistributionKind) String() string {
	return proto.EnumName(DistributionKind_name, int32(x))
}
func (DistributionKind) EnumDescriptor() ([]byte, []int) { return fileDescriptorData, []int{0} }

// Record is an observed distribution over some time period with some
// additional data about observed minimums and maximums.
type Record struct {
	// start and end time in seconds since unix epoch utc
	StartTime int64 `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   int64 `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// the number of observations in the distribution
	Observations int64 `protobuf:"varint,11,opt,name=observations,proto3" json:"observations,omitempty"`
	// a serialized distribution. the kind tells us which type of distribution
	// it is.
	Distribution     []byte           `protobuf:"bytes,3,opt,name=distribution,proto3" json:"distribution,omitempty"`
	DistributionKind DistributionKind `protobuf:"varint,10,opt,name=distribution_kind,json=distributionKind,proto3,enum=sm.rothko.data.DistributionKind" json:"distribution_kind,omitempty"`
	// minimum and maximum values observed
	Min   float64 `protobuf:"fixed64,4,opt,name=min,proto3" json:"min,omitempty"`
	MinId []byte  `protobuf:"bytes,12,opt,name=min_id,json=minId,proto3" json:"min_id,omitempty"`
	Max   float64 `protobuf:"fixed64,5,opt,name=max,proto3" json:"max,omitempty"`
	MaxId []byte  `protobuf:"bytes,13,opt,name=max_id,json=maxId,proto3" json:"max_id,omitempty"`
	// how many records have been merged into this.
	Merged int64 `protobuf:"varint,9,opt,name=merged,proto3" json:"merged,omitempty"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (m *Record) String() string            { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptorData, []int{0} }

func init() {
	proto.RegisterType((*Record)(nil), "sm.rothko.data.Record")
	proto.RegisterEnum("sm.rothko.data.DistributionKind", DistributionKind_name, DistributionKind_value)
}
func (m *Record) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Record) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.StartTime != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintData(dAtA, i, uint64(m.StartTime))
	}
	if m.EndTime != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintData(dAtA, i, uint64(m.EndTime))
	}
	if len(m.Distribution) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintData(dAtA, i, uint64(len(m.Distribution)))
		i += copy(dAtA[i:], m.Distribution)
	}
	if m.Min != 0 {
		dAtA[i] = 0x21
		i++
		i = encodeFixed64Data(dAtA, i, uint64(math.Float64bits(float64(m.Min))))
	}
	if m.Max != 0 {
		dAtA[i] = 0x29
		i++
		i = encodeFixed64Data(dAtA, i, uint64(math.Float64bits(float64(m.Max))))
	}
	if m.Merged != 0 {
		dAtA[i] = 0x48
		i++
		i = encodeVarintData(dAtA, i, uint64(m.Merged))
	}
	if m.DistributionKind != 0 {
		dAtA[i] = 0x50
		i++
		i = encodeVarintData(dAtA, i, uint64(m.DistributionKind))
	}
	if m.Observations != 0 {
		dAtA[i] = 0x58
		i++
		i = encodeVarintData(dAtA, i, uint64(m.Observations))
	}
	if len(m.MinId) > 0 {
		dAtA[i] = 0x62
		i++
		i = encodeVarintData(dAtA, i, uint64(len(m.MinId)))
		i += copy(dAtA[i:], m.MinId)
	}
	if len(m.MaxId) > 0 {
		dAtA[i] = 0x6a
		i++
		i = encodeVarintData(dAtA, i, uint64(len(m.MaxId)))
		i += copy(dAtA[i:], m.MaxId)
	}
	return i, nil
}

func encodeFixed64Data(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Data(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintData(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Record) Size() (n int) {
	var l int
	_ = l
	if m.StartTime != 0 {
		n += 1 + sovData(uint64(m.StartTime))
	}
	if m.EndTime != 0 {
		n += 1 + sovData(uint64(m.EndTime))
	}
	l = len(m.Distribution)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	if m.Min != 0 {
		n += 9
	}
	if m.Max != 0 {
		n += 9
	}
	if m.Merged != 0 {
		n += 1 + sovData(uint64(m.Merged))
	}
	if m.DistributionKind != 0 {
		n += 1 + sovData(uint64(m.DistributionKind))
	}
	if m.Observations != 0 {
		n += 1 + sovData(uint64(m.Observations))
	}
	l = len(m.MinId)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	l = len(m.MaxId)
	if l > 0 {
		n += 1 + l + sovData(uint64(l))
	}
	return n
}

func sovData(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozData(x uint64) (n int) {
	return sovData(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Record) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Record: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Record: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			m.StartTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartTime |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			m.EndTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndTime |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Distribution", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Distribution = append(m.Distribution[:0], dAtA[iNdEx:postIndex]...)
			if m.Distribution == nil {
				m.Distribution = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Min", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 8
			v = uint64(dAtA[iNdEx-8])
			v |= uint64(dAtA[iNdEx-7]) << 8
			v |= uint64(dAtA[iNdEx-6]) << 16
			v |= uint64(dAtA[iNdEx-5]) << 24
			v |= uint64(dAtA[iNdEx-4]) << 32
			v |= uint64(dAtA[iNdEx-3]) << 40
			v |= uint64(dAtA[iNdEx-2]) << 48
			v |= uint64(dAtA[iNdEx-1]) << 56
			m.Min = float64(math.Float64frombits(v))
		case 5:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Max", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 8
			v = uint64(dAtA[iNdEx-8])
			v |= uint64(dAtA[iNdEx-7]) << 8
			v |= uint64(dAtA[iNdEx-6]) << 16
			v |= uint64(dAtA[iNdEx-5]) << 24
			v |= uint64(dAtA[iNdEx-4]) << 32
			v |= uint64(dAtA[iNdEx-3]) << 40
			v |= uint64(dAtA[iNdEx-2]) << 48
			v |= uint64(dAtA[iNdEx-1]) << 56
			m.Max = float64(math.Float64frombits(v))
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Merged", wireType)
			}
			m.Merged = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Merged |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionKind", wireType)
			}
			m.DistributionKind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DistributionKind |= (DistributionKind(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Observations", wireType)
			}
			m.Observations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Observations |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinId = append(m.MinId[:0], dAtA[iNdEx:postIndex]...)
			if m.MinId == nil {
				m.MinId = []byte{}
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthData
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxId = append(m.MaxId[:0], dAtA[iNdEx:postIndex]...)
			if m.MaxId == nil {
				m.MaxId = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipData(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowData
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthData
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowData
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipData(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthData = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowData   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("data.proto", fileDescriptorData) }

var fileDescriptorData = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xb1, 0x6e, 0xfa, 0x30,
	0x10, 0xc6, 0x31, 0x84, 0x24, 0x1c, 0xfc, 0x91, 0xff, 0x96, 0x8a, 0xdc, 0x4a, 0x8d, 0x22, 0xa6,
	0xa8, 0x55, 0x83, 0xd4, 0xbe, 0x41, 0xc5, 0x02, 0x55, 0x97, 0x88, 0xa9, 0x0b, 0x72, 0xb0, 0x1b,
	0x2c, 0x64, 0xbb, 0x4a, 0x4c, 0x95, 0x47, 0x64, 0xec, 0xd2, 0xbd, 0xe5, 0x49, 0xaa, 0x18, 0x06,
	0x60, 0xbb, 0xef, 0xf7, 0x9d, 0x7d, 0xf7, 0xe9, 0x00, 0x38, 0xb3, 0x2c, 0xfd, 0x28, 0x8d, 0x35,
	0x64, 0x58, 0xa9, 0xb4, 0x34, 0x76, 0xbd, 0x31, 0x69, 0x43, 0x6f, 0x1e, 0x0a, 0x69, 0xd7, 0xdb,
	0x3c, 0x5d, 0x19, 0x35, 0x29, 0x4c, 0x61, 0x26, 0xae, 0x2d, 0xdf, 0xbe, 0x3b, 0xe5, 0x84, 0xab,
	0x0e, 0xcf, 0xc7, 0xdf, 0x6d, 0xf0, 0x33, 0xb1, 0x32, 0x25, 0x27, 0xb7, 0x00, 0x95, 0x65, 0xa5,
	0x5d, 0x5a, 0xa9, 0x04, 0x45, 0x31, 0x4a, 0x3a, 0x59, 0xcf, 0x91, 0x85, 0x54, 0x82, 0x5c, 0x43,
	0x28, 0x34, 0x3f, 0x98, 0x6d, 0x67, 0x06, 0x42, 0x73, 0x67, 0x8d, 0x61, 0xc0, 0x65, 0x65, 0x4b,
	0x99, 0x6f, 0xad, 0x34, 0x9a, 0x76, 0x62, 0x94, 0x0c, 0xb2, 0x33, 0x46, 0x30, 0x74, 0x94, 0xd4,
	0xd4, 0x8b, 0x51, 0x82, 0xb2, 0xa6, 0x74, 0x84, 0xd5, 0xb4, 0x7b, 0x24, 0xac, 0x26, 0x23, 0xf0,
	0x95, 0x28, 0x0b, 0xc1, 0x69, 0xcf, 0x0d, 0x38, 0x2a, 0xf2, 0x0a, 0xff, 0x4f, 0xff, 0x5a, 0x6e,
	0xa4, 0xe6, 0x14, 0x62, 0x94, 0x0c, 0x1f, 0xe3, 0xf4, 0x3c, 0x7f, 0x3a, 0x3d, 0x69, 0x7c, 0x91,
	0x9a, 0x67, 0x98, 0x5f, 0x90, 0x66, 0x5d, 0x93, 0x57, 0xa2, 0xfc, 0x64, 0x0d, 0xaa, 0x68, 0xdf,
	0x0d, 0x3b, 0x63, 0xe4, 0x0a, 0x7c, 0x25, 0xf5, 0x52, 0x72, 0x3a, 0x70, 0x61, 0xba, 0x4a, 0xea,
	0x19, 0x77, 0x98, 0xd5, 0x0d, 0xfe, 0x77, 0xc4, 0xac, 0x9e, 0xf1, 0xb9, 0x17, 0xfa, 0x38, 0x98,
	0x7b, 0x61, 0x80, 0xc3, 0xb9, 0x17, 0x86, 0xb8, 0x77, 0x77, 0x0f, 0xf8, 0x72, 0x13, 0x02, 0xe0,
	0x67, 0x4c, 0x73, 0xa3, 0x70, 0x8b, 0xf4, 0x21, 0x58, 0x4c, 0x65, 0x21, 0x2a, 0x8b, 0xd1, 0xf3,
	0x68, 0xf7, 0x1b, 0xb5, 0x76, 0xfb, 0x08, 0x7d, 0xed, 0x23, 0xf4, 0xb3, 0x8f, 0xd0, 0x9b, 0xd7,
	0x64, 0xc9, 0x7d, 0x77, 0xa3, 0xa7, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x89, 0x42, 0xca, 0x53,
	0xf0, 0x01, 0x00, 0x00,
}
