// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: record.proto

/*
	Package data is a generated protocol buffer package.

	It is generated from these files:
		record.proto

	It has these top-level messages:
		Record
*/
package data

import fmt "fmt"
import math "math"

import binary "encoding/binary"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.

// Record is an observed distribution over some time period with some
// additional data about observed minimums and maximums.
type Record struct {
	// start and end time in seconds since unix epoch utc
	StartTime int64 `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   int64 `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// the number of observations in the distribution
	Observations int64 `protobuf:"varint,3,opt,name=observations,proto3" json:"observations,omitempty"`
	// a serialized distribution. the kind tells us which type of distribution
	// it is.
	Distribution []byte `protobuf:"bytes,4,opt,name=distribution,proto3" json:"distribution,omitempty"`
	Kind         string `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	// minimum and maximum values observed
	Min   float64 `protobuf:"fixed64,6,opt,name=min,proto3" json:"min,omitempty"`
	Max   float64 `protobuf:"fixed64,7,opt,name=max,proto3" json:"max,omitempty"`
	MinId []byte  `protobuf:"bytes,8,opt,name=min_id,json=minId,proto3" json:"min_id,omitempty"`
	MaxId []byte  `protobuf:"bytes,9,opt,name=max_id,json=maxId,proto3" json:"max_id,omitempty"`
	// how many records have been merged into this.
	Merged int64 `protobuf:"varint,10,opt,name=merged,proto3" json:"merged,omitempty"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptorRecord, []int{0} }

func init() {
}
func (m *Record) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Record) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.StartTime != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintRecord(dAtA, i, uint64(m.StartTime))
	}
	if m.EndTime != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintRecord(dAtA, i, uint64(m.EndTime))
	}
	if m.Observations != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintRecord(dAtA, i, uint64(m.Observations))
	}
	if len(m.Distribution) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintRecord(dAtA, i, uint64(len(m.Distribution)))
		i += copy(dAtA[i:], m.Distribution)
	}
	if len(m.Kind) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintRecord(dAtA, i, uint64(len(m.Kind)))
		i += copy(dAtA[i:], m.Kind)
	}
	if m.Min != 0 {
		dAtA[i] = 0x31
		i++
		binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Min))))
		i += 8
	}
	if m.Max != 0 {
		dAtA[i] = 0x39
		i++
		binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Max))))
		i += 8
	}
	if len(m.MinId) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintRecord(dAtA, i, uint64(len(m.MinId)))
		i += copy(dAtA[i:], m.MinId)
	}
	if len(m.MaxId) > 0 {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintRecord(dAtA, i, uint64(len(m.MaxId)))
		i += copy(dAtA[i:], m.MaxId)
	}
	if m.Merged != 0 {
		dAtA[i] = 0x50
		i++
		i = encodeVarintRecord(dAtA, i, uint64(m.Merged))
	}
	return i, nil
}

func encodeVarintRecord(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Record) Size() (n int) {
	var l int
	_ = l
	if m.StartTime != 0 {
		n += 1 + sovRecord(uint64(m.StartTime))
	}
	if m.EndTime != 0 {
		n += 1 + sovRecord(uint64(m.EndTime))
	}
	if m.Observations != 0 {
		n += 1 + sovRecord(uint64(m.Observations))
	}
	l = len(m.Distribution)
	if l > 0 {
		n += 1 + l + sovRecord(uint64(l))
	}
	l = len(m.Kind)
	if l > 0 {
		n += 1 + l + sovRecord(uint64(l))
	}
	if m.Min != 0 {
		n += 9
	}
	if m.Max != 0 {
		n += 9
	}
	l = len(m.MinId)
	if l > 0 {
		n += 1 + l + sovRecord(uint64(l))
	}
	l = len(m.MaxId)
	if l > 0 {
		n += 1 + l + sovRecord(uint64(l))
	}
	if m.Merged != 0 {
		n += 1 + sovRecord(uint64(m.Merged))
	}
	return n
}

func sovRecord(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozRecord(x uint64) (n int) {
	return sovRecord(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Record) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRecord
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Record: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Record: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			m.StartTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartTime |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			m.EndTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndTime |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Observations", wireType)
			}
			m.Observations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Observations |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Distribution", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRecord
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Distribution = append(m.Distribution[:0], dAtA[iNdEx:postIndex]...)
			if m.Distribution == nil {
				m.Distribution = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Kind = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Min", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Min = float64(math.Float64frombits(v))
		case 7:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Max", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Max = float64(math.Float64frombits(v))
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRecord
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinId = append(m.MinId[:0], dAtA[iNdEx:postIndex]...)
			if m.MinId == nil {
				m.MinId = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRecord
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxId = append(m.MaxId[:0], dAtA[iNdEx:postIndex]...)
			if m.MaxId == nil {
				m.MaxId = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Merged", wireType)
			}
			m.Merged = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Merged |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRecord(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRecord
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRecord(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRecord
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRecord
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRecord
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthRecord
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowRecord
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipRecord(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthRecord = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRecord   = fmt.Errorf("proto: integer overflow")
)


var fileDescriptorRecord = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xd0, 0xb1, 0x4e, 0xeb, 0x30,
	0x14, 0x06, 0xe0, 0xba, 0x49, 0xd3, 0xe6, 0x28, 0xba, 0xba, 0xb2, 0x00, 0x19, 0x24, 0xac, 0x28,
	0x53, 0xa6, 0x30, 0xf0, 0x06, 0x6c, 0x5d, 0x23, 0x26, 0x96, 0xca, 0xc1, 0x56, 0xb0, 0x2a, 0xdb,
	0xc8, 0x31, 0x28, 0x8f, 0xc0, 0xa3, 0x75, 0x64, 0x64, 0xa4, 0x99, 0x18, 0x79, 0x04, 0xe4, 0xd3,
	0x2c, 0xdd, 0x7e, 0x7f, 0xff, 0xb1, 0x65, 0x1d, 0x28, 0xbc, 0x7a, 0x76, 0x5e, 0x36, 0xaf, 0xde,
	0x05, 0x47, 0xff, 0x0d, 0xa6, 0xf1, 0x2e, 0xbc, 0xec, 0x5d, 0x23, 0x45, 0x10, 0x37, 0x17, 0xbd,
	0xeb, 0x1d, 0x56, 0x77, 0x31, 0x9d, 0xa6, 0xaa, 0x8f, 0x25, 0x64, 0x2d, 0x5e, 0xa3, 0xb7, 0x00,
	0x43, 0x10, 0x3e, 0xec, 0x82, 0x36, 0x8a, 0x91, 0x92, 0xd4, 0x49, 0x9b, 0xa3, 0x3c, 0x6a, 0xa3,
	0xe8, 0x35, 0x6c, 0x94, 0x95, 0xa7, 0x72, 0x89, 0xe5, 0x5a, 0x59, 0x89, 0x55, 0x05, 0x85, 0xeb,
	0x06, 0xe5, 0xdf, 0x45, 0xd0, 0xce, 0x0e, 0x2c, 0xc1, 0xfa, 0xcc, 0xe2, 0x8c, 0xd4, 0x43, 0xf0,
	0xba, 0x7b, 0x8b, 0xc0, 0xd2, 0x92, 0xd4, 0x45, 0x7b, 0x66, 0x94, 0x42, 0xba, 0xd7, 0x56, 0xb2,
	0x55, 0x49, 0xea, 0xbc, 0xc5, 0x4c, 0xff, 0x43, 0x62, 0xb4, 0x65, 0x59, 0x49, 0x6a, 0xd2, 0xc6,
	0x88, 0x22, 0x46, 0xb6, 0x9e, 0x45, 0x8c, 0xf4, 0x12, 0x32, 0xa3, 0xed, 0x4e, 0x4b, 0xb6, 0xc1,
	0x57, 0x57, 0x46, 0xdb, 0xad, 0x44, 0x16, 0x63, 0xe4, 0x7c, 0x66, 0x31, 0x6e, 0x25, 0xbd, 0x82,
	0xcc, 0x28, 0xdf, 0x2b, 0xc9, 0x00, 0xff, 0x39, 0x9f, 0x1e, 0xaa, 0xc3, 0x91, 0x2f, 0xbe, 0x8e,
	0x7c, 0x71, 0x98, 0x38, 0xf9, 0x9c, 0x38, 0xf9, 0x9e, 0x38, 0xf9, 0x99, 0xf8, 0xe2, 0x77, 0xe2,
	0xe4, 0x29, 0x8d, 0x4b, 0xec, 0x32, 0xdc, 0xda, 0xfd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xae,
	0xc6, 0x26, 0x66, 0x6b, 0x01, 0x00, 0x00,
}
